# Remove version declaration as it's obsolete

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_VERSION=1.0.32
      - NEXT_PUBLIC_SUPABASE_URL=https://zdleickljellmrlqeyee.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbGVpY2tsamVsbG1ybHFleWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDg5NjQsImV4cCI6MjA3MzQyNDk2NH0.B3iqC5O2L1FgS4Ib7_ogsit8fHSRkwGMZXYz2NmEnTc
    restart: unless-stopped
    profiles:
      - prod

  # Alternative: Production service without exposed ports (for Nginx Proxy Manager)
  app-prod-internal:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_VERSION=1.0.32
      - NEXT_PUBLIC_SUPABASE_URL=https://zdleickljellmrlqeyee.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbGVpY2tsamVsbG1ybHFleWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDg5NjQsImV4cCI6MjA3MzQyNDk2NH0.B3iqC5O2L1FgS4Ib7_ogsit8fHSRkwGMZXYz2NmEnTc
    restart: unless-stopped
    profiles:
      - prod-internal 